wits_version:
    resource: "@WitsVersionBundle/Resources/config/routing.xml"
    prefix:   /

wits_project:
    resource: "@WitsProjectBundle/Resources/config/routing.xml"

wits_issue:
    resource: "@WitsIssueBundle/Resources/config/routing.xml"

wits_user:
    resource: "@WitsUserBundle/Resources/config/routing.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
